# Generated by Django 5.2.3 on 2025-08-07 13:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount_created_at_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='likepost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentAuthor', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
        ),
    ]
