# Generated by Django 5.2.3 on 2025-08-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_myfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilebackgroud',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
