# Generated by Django 5.2.3 on 2025-08-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_profilebackgroud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profilebackgroud',
            new_name='profilebackground',
        ),
    ]
