# Generated by Django 5.2.3 on 2025-08-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_profilebackgroud_profile_profilebackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
