# Generated by Django 5.2.3 on 2025-08-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_user_confirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_confirmed',
            new_name='email_confirmed',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='private_public',
            field=models.BooleanField(default=False),
        ),
    ]
