# Generated by Django 5.2.3 on 2025-08-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_user_confirmed_profile_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(blank=True),
        ),
    ]
