from django.urls import include, path

from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('settings',views.settings,name='settings'),
    path('upload', views.upload, name='uplaod'),
    path('follow', views.follow, name='follow'),
    path('search', views.search, name='search'),
    path('profile/<str:pk>', views.profile, name='profile'),
    path('following/<str:pk>', views.following, name='following'),
    path('followers/<str:pk>', views.followers, name='followers'),
    path('like-post', views.like_post, name='like-post'),
    path('signup', views.signup, name='signup'),
    path('signin', views.signin, name='signin'),
    path('logout', views.signin, name='logout'),
    path('delete-post/', views.delete_post, name='delete_post'),
    path('explore/', views.explore, name='explore'),
    path('post/<str:post_id>', views.post, name='post'),
    path('comment/<str:post_id>', views.comment, name='comment'),
    path('comment/delete/<str:post_id>', views.commentDelete, name='comment_delete'),
    path('my-favorite', views.myFavorite, name='my_favorite'),
    path('my-favorite/add/<str:post_id>', views.myFavoriteAdd, name='my_favorite'),
    path('confirm-email', views.comfirmEmail, name='confirm_email'),
    path('verify-email', views.verifyEmail, name='verify_email'),
    path('verify-phone', views.verifyPhone, name='verify_phone'),
    path('confirm-phone', views.confirmPhone, name='confirm_phone'),
    path('change-password', views.changePassword, name='change_password'),
    path('end-session/<str:session_key>/', views.end_session, name='end_session'),
    path('forgot-password', views.forgotPassword, name='forgot_password'),
    path('private-public', views.privatePublic, name='private_public'),
    path('accept-request/<str:pk>/', views.acceptRequest, name='accept-request'),
    path("message/<str:room_name>/", views.messageRoom, name="message_room"),
    path("send_message/<str:room_name>/", views.messageSend, name="send_message"),
    path("messages", views.messagesChat, name="messages"),
]